config/routes.rb
Rails.application.routes.draw do
  resources :users

  get '/id3s/query'
  get '/uriinfos/query'

  resources :uriinfos
  resources :id3s

  root 'id3s#query'

end

app/models/id3.rb
class Id3
  include Mongoid::Document
  field :title, type: String
  field :artist, type: String
  field :album, type: String
  has_and_belongs_to_many :uriinfos
  accepts_nested_attributes_for :uriinfos
end

app/models/uriinfo.rb
class Uriinfo
  include Mongoid::Document
  field :name, type: String
  field :uri, type: String
  field :originurl, type: String
  has_and_belongs_to_many :id3s
end

app/models/user.rb
class User
  include Mongoid::Document
  field :username, type: String
  field :password, type: String

  validates_uniqueness_of :name
  index({ username: 1 } , { unique: true })
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/id3s_controller.rb
class Id3sController < ApplicationController
  before_action :set_id3, only: [:show, :edit, :update, :destroy]

  def query
    @query = params[:q]
    if @query.nil? || @query.empty?
      return
    end
    regex = /#{@query}/i
    @id3s = Id3.or({title: regex}, {artist: regex}, {album: regex})
  end

  # GET /id3s
  # GET /id3s.json
  def index
    @id3s = Id3.all
  end

  # GET /id3s/1
  # GET /id3s/1.json
  def show
  end

  # GET /id3s/new
  def new
    @id3 = Id3.new
  end

  # GET /id3s/1/edit
  def edit
    @uriinfos = Uriinfo.all
  end

  # POST /id3s
  # POST /id3s.json
  def create
    @id3 = Id3.new(id3_params)

    respond_to do |format|
      if @id3.save
        format.html { redirect_to @id3, notice: 'Id3 was successfully created.' }
        format.json { render :show, status: :created, location: @id3 }
      else
        format.html { render :new }
        format.json { render json: @id3.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /id3s/1
  # PATCH/PUT /id3s/1.json
  def update
    respond_to do |format|
      if @id3.update(id3_params)
        format.html { redirect_to @id3, notice: 'Id3 was successfully updated.' }
        format.json { render :show, status: :ok, location: @id3 }
      else
        format.html { render :edit }
        format.json { render json: @id3.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /id3s/1
  # DELETE /id3s/1.json
  def destroy
    @id3.destroy
    respond_to do |format|
      format.html { redirect_to id3s_url, notice: 'Id3 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_id3
      @id3 = Id3.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def id3_params
      params.require(:id3).permit(:title, :artist, :album, :uriinfo_ids => [])
    end
end

app/controllers/proxy_controller.rb
class ProxyController < ApplicationController
  include ProxyHelper

  def hotlink
    puts params[:domain]+params[:id]
    gethotlink params[:domain], params[:id]
  end
end

app/controllers/uriinfos_controller.rb
class UriinfosController < ApplicationController
  include UriinfosHelper
  before_action :set_uriinfo, only: [:show, :edit, :update, :destroy]

  def query
    @query = params[:q]
    if @query.nil? || @query.empty?
      return
    end
    @uriinfo = geturiinfo(@query)
    regex = /#{@query}/i
    @id3s = Id3.or({title: regex}, {artist: regex}, {album: regex})
  end

  # GET /uriinfos
  # GET /uriinfos.json
  def index
    @uriinfos = Uriinfo.all
  end

  # GET /uriinfos/1
  # GET /uriinfos/1.json
  def show
  end

  # GET /uriinfos/new
  def new
    @uriinfo = Uriinfo.new
  end

  # GET /uriinfos/1/edit
  def edit
  end

  # POST /uriinfos
  # POST /uriinfos.json
  def create
    @uriinfo = Uriinfo.new(uriinfo_params)

    respond_to do |format|
      if @uriinfo.save
        format.html { redirect_to @uriinfo, notice: 'Uriinfo was successfully created.' }
        format.json { render :show, status: :created, location: @uriinfo }
      else
        format.html { render :new }
        format.json { render json: @uriinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uriinfos/1
  # PATCH/PUT /uriinfos/1.json
  def update
    respond_to do |format|
      if @uriinfo.update(uriinfo_params)
        format.html { redirect_to @uriinfo, notice: 'Uriinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @uriinfo }
      else
        format.html { render :edit }
        format.json { render json: @uriinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uriinfos/1
  # DELETE /uriinfos/1.json
  def destroy
    @uriinfo.destroy
    respond_to do |format|
      format.html { redirect_to uriinfos_url, notice: 'Uriinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uriinfo
      @uriinfo = Uriinfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uriinfo_params
      params.require(:uriinfo).permit(:name, :uri, :originurl)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/id3s_helper.rb
module Id3sHelper
end

app/helpers/proxy_helper.rb
require 'open-uri'
require 'stringio'
require 'net/http'
require 'uri'
require 'json'
require 'hashie'

module ProxyHelper
  def gethotlink(domain, songid)
    if domain == "baidu"
      url = URI.parse("http://play.baidu.com/data/cloud/songlink")
      http = Net::HTTP.new(url.host, url.port)
      req = Net::HTTP::Post.new(url.path) # init a request with the url
      req["User-Agent"] = "Chrome"
      req.set_form_data({'songIds' => songid})
      res = http.request(req) # load the mp3 file
      obj = Hashie::Mash.new JSON.parse res.body
      redirect_to obj.data.songList[0].songLink
    else
      render :status => 404
    end
  end
end

app/helpers/uriinfos_helper.rb
require 'open-uri'
require 'stringio'
require 'net/http'
require 'uri'
require 'mp3info'

module UriinfosHelper
  def geturiinfo(uri)
    url = URI.parse(uri)
    http = Net::HTTP.new(url.host, url.port)
    req = Net::HTTP::Get.new(url.path + '?' + url.query) # init a request with the url
    req.range = (0..4096) # limit the load to only 4096 bytes
    res = http.request(req) # load the mp3 file
    child = {} # prepare an empty array to store the metadata we grab
    Mp3Info.open( StringIO.open(res.body) ) do |m|  #do the parsing
        child['title'] = m.tag.title
        child['album'] = m.tag.album
        child['artist'] = m.tag.artist
        child['length'] = m.length
    end
    child
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/id3s/_form.html.erb
<%= form_for(@id3) do |f| %>
  <% if @id3.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@id3.errors.count, "error") %> prohibited this id3 from being saved:</h2>

      <ul>
      <% @id3.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label "All Uriinfos" %><br />
    <%= f.collection_select :uriinfo_ids, Uriinfo.all, :id, :uri, {:include_blank => 'Select', include_hidden: false}, {:multiple => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/id3s/edit.html.erb
<h1>Editing Id3</h1>

<%= render 'form' %>

<%= link_to 'Show', @id3 %> |
<%= link_to 'Back', id3s_path %>

app/views/id3s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Id3s</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @id3s.each do |id3| %>
      <tr>
        <td><%= id3.title %></td>
        <td><%= id3.artist %></td>
        <td><%= id3.album %></td>
        <td><%= link_to 'Show', id3 %></td>
        <td><%= link_to 'Edit', edit_id3_path(id3) %></td>
        <td><%= link_to 'Destroy', id3, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Id3', new_id3_path %>

app/views/id3s/new.html.erb
<h1>New Id3</h1>

<%= render 'form' %>

<%= link_to 'Back', id3s_path %>

app/views/id3s/query.html.erb
<div class="container">
  <main>
    <form class="form-search">
      <h1>Id3#index</h1>
      <input type="text" name="q" class="form-control" placeholder="Search the id3tag info" <% if @query %>value="<%= @query %>"<% end %> autofocus>
      <% if @query %>
      <div>
        <% if @id3s %>
        <h5><%= @id3s.length %> records.</h5>
        <% end %>
      </div>
      <% end %>
    </form>
    <table class="musiclist table table-striped table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Artist</th>
          <th>Album</th>
        </tr>
      </thead>
      <tbody>
      <% @id3s||=[] %>
      <% @id3s.each do |id3| %>
        <tr>
          <td><%= id3.title %></td>
          <td><%= id3.artist %></td>
          <td><%= id3.album %></td>
          <!--td>
            <%= link_to 'Show', id3 %>
            <%= link_to 'Edit', edit_id3_path(id3) %>
            <%= link_to 'Destroy', id3, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td-->
        </tr>
      <% end %>
      </tbody>
    </table>
  </main>
</div>

app/views/id3s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @id3.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @id3.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @id3.album %>
</p>

<p>
  <strong>Uriinfos:</strong>
  <% @id3.uriinfos.each do |uri| %>
    <%= link_to uri.name, uri.uri %>
  <% end %>
</p>

<%= link_to 'Edit', edit_id3_path(@id3) %> |
<%= link_to 'Back', id3s_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Id3tag</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uriinfos/_form.html.erb
<%= form_for(@uriinfo) do |f| %>
  <% if @uriinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uriinfo.errors.count, "error") %> prohibited this uriinfo from being saved:</h2>

      <ul>
      <% @uriinfo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :uri %><br>
    <%= f.text_field :uri %>
  </div>
  <div class="field">
    <%= f.label :originurl %><br>
    <%= f.text_field :originurl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uriinfos/edit.html.erb
<h1>Editing Uriinfo</h1>

<%= render 'form' %>

<%= link_to 'Show', @uriinfo %> |
<%= link_to 'Back', uriinfos_path %>

app/views/uriinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Uriinfos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Uri</th>
      <th>Originurl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uriinfos.each do |uriinfo| %>
      <tr>
        <td><%= uriinfo.name %></td>
        <td><%= uriinfo.uri %></td>
        <td><%= uriinfo.originurl %></td>
        <td><%= link_to 'Show', uriinfo %></td>
        <td><%= link_to 'Edit', edit_uriinfo_path(uriinfo) %></td>
        <td><%= link_to 'Destroy', uriinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uriinfo', new_uriinfo_path %>

app/views/uriinfos/new.html.erb
<h1>New Uriinfo</h1>

<%= render 'form' %>

<%= link_to 'Back', uriinfos_path %>

app/views/uriinfos/query.html.erb
<div class="container">
  <main>
    <form class="form-search">
      <h1>Uriinfo#index</h1>
      <input type="text" name="q" class="form-control" placeholder="Enter the uri to parse" <% if @query %>value="<%= @query %>"<% end %> autofocus>
      <% if @query %>
      <div>
        <% if @uriinfo %>
        <h5><%= @uriinfo %> find.</h5>
        <% end %>
      </div>
      <% end %>
    </form>
    <table class="musiclist table table-striped table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Artist</th>
          <th>Album</th>
        </tr>
      </thead>
      <tbody>
      <% @id3s||=[] %>
      <% @id3s.each do |id3| %>
        <tr>
          <td><%= id3.title %></td>
          <td><%= id3.artist %></td>
          <td><%= id3.album %></td>
          <!--td>
            <%= link_to 'Show', id3 %>
            <%= link_to 'Edit', edit_id3_path(id3) %>
            <%= link_to 'Destroy', id3, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td-->
        </tr>
      <% end %>
      </tbody>
    </table>
  </main>
</div>

app/views/uriinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @uriinfo.name %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @uriinfo.uri %>
</p>

<p>
  <strong>Originurl:</strong>
  <%= @uriinfo.originurl %>
</p>

<%= link_to 'Edit', edit_uriinfo_path(@uriinfo) %> |
<%= link_to 'Back', uriinfos_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>